### ISSUE TITLE
import to ldb interruption, raise ldb E056 error

### ISSUE THREAD

**Issue by DRong1121** [scanoss/ldb#9] opened 2023-04-11 07:15 UTC
I am using the 'minr' tool to import a local project to ldb, I executed 3 commands as follows:
1) minr -d ...  -u /mnt/my_project.zip -o /opt
2) minr -z /opt/mined
3) minr -i /opt/mined
The 3rd command encountered a keyboard interruption, and the import step stopped.
I re-executed the above 3 commands, but the 3rd command raised an ldb E056 error as follows:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/20332907/231084146-817ca677-cb5e-4497-9913-9a89d9489079.png">

The project, /mnt/my_project.zip, cannot be imported anymore.
Is there any solution to my problem?

**Comment by mscasso-scanoss** [comment] 2023-04-17 10:09
Dear @DRong1121, 
We apologize for the inconvenience you're experiencing. We couldn't reproduce the issue, but have you tried deleting the failed KB before importing it again using the command "rm -r /var/lib/ldb/oss"? It could be due to a broken sector during the aborted importation.
If the repository you're mining isn't private, can you share the CSV with us? We want to reproduce the issue and find a resolution for you.

I'm closing this issue because it is duplicated. Please, continue the talk here: https://github.com/scanoss/minr/issues/30

**Closed by mscasso-scanoss** 2023-04-17 10:09 UTC
